#!/usr/bin/env python3
"""Validate normative database against published literature findings.

Checks that computed norms are consistent with well-established EEG
findings from the published literature. These are not exact-number
comparisons (different pipelines produce different absolute values)
but directional and magnitude checks that catch pipeline errors.

References:
  - Dustman et al. (1999) — lifespan EEG changes
  - Barry et al. (2007) — EO vs EC differences
  - Voytek et al. (2015) — aperiodic slope and aging
  - Corcoran et al. (2018) — IAF methods
  - Hill et al. (2022) — developmental aperiodic changes
  - Schaworonkow & Bhatt (2023) — aperiodic parameters across age
  - Craiu et al. (2025) — periodic and aperiodic normative characterization

Usage:
    python scripts/validate_literature.py ./norms_output/subjects \
        --output ./literature_validation.json
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np
from scipy import stats as scipy_stats


class _NumpyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, (np.bool_, np.integer)):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return super().default(obj)

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from open_normative.normative import build_normative, _DEFAULT_AGE_BINS

logger = logging.getLogger("validate_literature")


def load_subjects(subjects_dir: Path) -> list[dict]:
    """Load all subject checkpoint JSONs."""
    subjects = []
    for fpath in sorted(subjects_dir.glob("*.json")):
        with open(fpath) as f:
            subjects.append(json.load(f))
    return subjects


# ── Reference checks ────────────────────────────────────────────────────


def check_alpha_posterior_dominance(norms) -> dict:
    """Alpha power should be maximal at posterior sites (O1, O2, Pz, P3, P4).

    This is a fundamental EEG finding — the alpha rhythm is generated by
    thalamocortical circuits and is strongest over occipital-parietal cortex.

    References:
        - Niedermeyer & da Silva (2005), Electroencephalography
        - Klimesch (1999), EEG alpha and theta oscillations
    """
    posterior = {"O1", "O2", "Pz", "P3", "P4"}
    anterior = {"Fp1", "Fp2", "Fz", "F3", "F4"}

    # Use relative_power (unit-independent) to avoid V²/Hz scale issues
    cells_alpha = [c for c in norms if c.band == "Alpha" and c.metric == "relative_power"]
    if not cells_alpha:
        cells_alpha = [c for c in norms if c.band == "Alpha" and c.metric == "absolute_power"]

    results = []
    for age_bin in sorted(set(c.bin for c in cells_alpha)):
        for cond in sorted(set(c.condition for c in cells_alpha)):
            bin_cells = [c for c in cells_alpha if c.bin == age_bin and c.condition == cond]
            post_means = [c.mean for c in bin_cells if c.channel in posterior]
            ant_means = [c.mean for c in bin_cells if c.channel in anterior]

            if post_means and ant_means:
                post_avg = np.mean(post_means)
                ant_avg = np.mean(ant_means)
                ratio = post_avg / ant_avg if ant_avg > 0 else None
                results.append({
                    "bin": age_bin,
                    "condition": cond,
                    "posterior_mean": round(post_avg, 4),
                    "anterior_mean": round(ant_avg, 4),
                    "post_ant_ratio": round(ratio, 2) if ratio else None,
                    "correct": ratio is not None and ratio > 1.0,
                })

    n_correct = sum(1 for r in results if r["correct"])
    violations = [r for r in results if not r["correct"]]

    return {
        "check": "Alpha posterior dominance",
        "description": "Alpha power should be higher at posterior (O1,O2,Pz,P3,P4) than anterior (Fp1,Fp2,Fz,F3,F4) sites",
        "reference": "Niedermeyer & da Silva (2005); Klimesch (1999)",
        "n_tested": len(results),
        "n_correct": n_correct,
        "pass": len(violations) == 0,
        "violations": violations[:5],
    }


def check_eo_ec_alpha(norms) -> dict:
    """Eyes-closed alpha should exceed eyes-open alpha (Berger effect).

    The alpha rhythm was the first EEG rhythm discovered (Hans Berger, 1929).
    It is suppressed by eye opening (visual cortex activation).
    Expected EC/EO ratio: 1.5-4x at posterior sites.

    References:
        - Barry et al. (2007) — EEG differences between EC and EO
        - Barry et al. (2009) — comprehensive EO/EC review
    """
    # Use relative_power (unit-independent)
    standard_channels = {
        "Fp1", "Fp2", "F7", "F3", "Fz", "F4", "F8",
        "T3", "C3", "Cz", "C4", "T4",
        "T5", "P3", "Pz", "P4", "T6", "O1", "O2",
    }
    cells_alpha = [
        c for c in norms
        if c.band == "Alpha" and c.metric == "relative_power"
        and c.channel in standard_channels
    ]
    if not cells_alpha:
        cells_alpha = [
            c for c in norms
            if c.band == "Alpha" and c.metric == "absolute_power"
            and c.channel in standard_channels
        ]

    by_key = {}
    for c in cells_alpha:
        key = (c.bin, c.channel)
        if key not in by_key:
            by_key[key] = {}
        by_key[key][c.condition] = c.mean

    results = []
    for (age_bin, channel), cond_means in sorted(by_key.items()):
        eo = cond_means.get("eo")
        ec = cond_means.get("ec")
        if eo is None or ec is None:
            continue
        if eo == 0 and ec == 0:
            continue
        ratio = ec / eo if eo > 0 else None
        results.append({
            "bin": age_bin,
            "channel": channel,
            "ec_mean": float(f"{ec:.6g}"),
            "eo_mean": float(f"{eo:.6g}"),
            "ec_eo_ratio": round(ratio, 2) if ratio else None,
            "correct": ratio is not None and ratio > 1.0,
        })

    n_correct = sum(1 for r in results if r["correct"])
    violations = [r for r in results if not r["correct"]]
    ratios = [r["ec_eo_ratio"] for r in results if r["ec_eo_ratio"]]

    return {
        "check": "Berger effect (EC > EO alpha)",
        "description": "Eyes-closed alpha power should exceed eyes-open at all sites. Expected ratio 1.5-4x at posterior sites.",
        "reference": "Berger (1929); Barry et al. (2007, 2009)",
        "n_tested": len(results),
        "n_correct": n_correct,
        "pass_rate": round(n_correct / len(results), 3) if results else None,
        "median_ec_eo_ratio": round(float(np.median(ratios)), 2) if ratios else None,
        "pass": n_correct / len(results) > 0.90 if results else False,
        "n_violations": len(violations),
        "violations": violations[:5],
    }


def check_aperiodic_exponent_range(norms) -> dict:
    """Aperiodic exponent should typically be 0.8-2.5 for healthy adults.

    The 1/f exponent reflects the balance of excitation/inhibition in
    cortical circuits. Values outside this range suggest pipeline issues.

    References:
        - Donoghue et al. (2020) — specparam paper
        - Voytek et al. (2015) — aging and 1/f slope
        - Schaworonkow & Bhatt (2023) — aperiodic parameters
    """
    cells = [c for c in norms if c.metric == "aperiodic_exponent" and c.n >= 5]

    results = []
    out_of_range = []
    for c in cells:
        in_range = 0.5 <= c.mean <= 3.0
        entry = {
            "bin": c.bin,
            "condition": c.condition,
            "channel": c.channel,
            "mean_exponent": round(c.mean, 3),
            "sd": round(c.sd, 3),
            "n": c.n,
            "in_expected_range": in_range,
        }
        results.append(entry)
        if not in_range:
            out_of_range.append(entry)

    return {
        "check": "Aperiodic exponent range",
        "description": "Mean aperiodic exponent should be 0.5-3.0 for healthy adults (typical: 1.0-2.0)",
        "reference": "Donoghue et al. (2020); Voytek et al. (2015)",
        "n_tested": len(results),
        "n_in_range": len(results) - len(out_of_range),
        "pass": len(out_of_range) == 0,
        "out_of_range": out_of_range[:5],
    }


def check_aperiodic_age_flattening(norms) -> dict:
    """Aperiodic exponent should decrease (flatten) with age.

    Older adults have flatter 1/f slopes (lower exponents), reflecting
    reduced inhibition and altered E/I balance.

    References:
        - Voytek et al. (2015) — 1/f slope flattening with age
        - Hill et al. (2022) — developmental aperiodic changes
        - Craiu et al. (2025) — -0.003 to -0.004 per year
    """
    cells = [
        c for c in norms
        if c.metric == "aperiodic_exponent" and c.channel == "Pz" and c.n >= 5
    ]

    results_by_cond = {}
    for cond in sorted(set(c.condition for c in cells)):
        cond_cells = sorted(
            [c for c in cells if c.condition == cond],
            key=lambda c: c.bin,
        )
        if len(cond_cells) < 3:
            continue

        midpoints = []
        means = []
        for c in cond_cells:
            lo, hi = c.bin.split("-")
            midpoints.append((int(lo) + int(hi)) / 2.0)
            means.append(c.mean)

        r, p = scipy_stats.pearsonr(midpoints, means)
        results_by_cond[cond] = {
            "bins": [c.bin for c in cond_cells],
            "exponent_means": [round(c.mean, 3) for c in cond_cells],
            "ns": [c.n for c in cond_cells],
            "correlation_r": round(float(r), 3),
            "correlation_p": round(float(p), 4),
            "negative_trend": r < 0,
        }

    return {
        "check": "Aperiodic exponent flattens with age",
        "description": "1/f exponent should decrease (flatten) with age at Pz",
        "reference": "Voytek et al. (2015); Craiu et al. (2025): ~-0.003/year",
        "pass": all(v["negative_trend"] for v in results_by_cond.values()) if results_by_cond else None,
        "by_condition": results_by_cond,
    }


def check_iaf_range(norms) -> dict:
    """Individual alpha frequency should be 8-13 Hz for healthy adults.

    IAF peaks around 10 Hz in young adults and declines ~0.015 Hz/year.

    References:
        - Klimesch (1999) — alpha oscillation frequency
        - Craiu et al. (2025) — IAF decline -0.015 Hz/year
        - Corcoran et al. (2018) — IAF estimation methods
    """
    cells = [
        c for c in norms
        if c.metric == "iaf_peak" and c.channel == "_subject" and c.n >= 5
    ]

    if not cells:
        return {
            "check": "IAF range",
            "description": "Global IAF should be 8-13 Hz",
            "pass": None,
            "note": "No IAF cells found (specparam may not be installed)",
        }

    results = []
    out_of_range = []
    for c in cells:
        in_range = 8.0 <= c.mean <= 13.0
        entry = {
            "bin": c.bin,
            "condition": c.condition,
            "mean_iaf": round(c.mean, 2),
            "sd": round(c.sd, 2),
            "n": c.n,
            "in_range": in_range,
        }
        results.append(entry)
        if not in_range:
            out_of_range.append(entry)

    return {
        "check": "IAF in expected range (8-13 Hz)",
        "description": "Mean IAF should be 8-13 Hz, peaking ~10 Hz in young adults, declining with age",
        "reference": "Klimesch (1999); Craiu et al. (2025): -0.015 Hz/year",
        "n_tested": len(results),
        "n_in_range": len(results) - len(out_of_range),
        "pass": len(out_of_range) == 0,
        "results": results,
    }


def check_theta_beta_ratio_range(norms) -> dict:
    """Theta/beta ratio should typically be 1.5-6.0 in healthy adults.

    Higher in children (developing brain), lower in adults.
    Elevated TBR is associated with ADHD in some (contested) literature.

    References:
        - Arns et al. (2013) — TBR meta-analysis
        - Snyder et al. (2015) — TBR in ADHD
    """
    # TBR is stored as band="Theta/Beta", metric="value" in the nested dict
    standard_channels = {
        "Fp1", "Fp2", "F7", "F3", "Fz", "F4", "F8",
        "T3", "C3", "Cz", "C4", "T4",
        "T5", "P3", "Pz", "P4", "T6", "O1", "O2",
    }
    cells = [
        c for c in norms
        if c.band == "Theta/Beta" and c.channel in standard_channels and c.n >= 5
    ]

    if not cells:
        return {
            "check": "Theta/Beta ratio range",
            "description": "Mean TBR should be 0.5-10.0",
            "pass": None,
            "note": "No Theta/Beta ratio cells found in norms",
        }

    results = []
    for c in cells:
        in_range = 0.5 <= c.mean <= 10.0
        results.append({
            "bin": c.bin,
            "condition": c.condition,
            "channel": c.channel,
            "mean_tbr": round(c.mean, 2),
            "n": c.n,
            "in_range": in_range,
        })

    out_of_range = [r for r in results if not r["in_range"]]

    return {
        "check": "Theta/Beta ratio range",
        "description": "Mean TBR should be 0.5-10.0 for healthy adults (typical: 1.5-4.0)",
        "reference": "Arns et al. (2013); Snyder et al. (2015)",
        "n_tested": len(results),
        "pass": len(out_of_range) == 0,
        "n_out_of_range": len(out_of_range),
        "out_of_range": out_of_range[:5],
    }


def check_relative_power_sums(norms) -> dict:
    """Relative power across non-overlapping bands should sum to ~1.0.

    Non-overlapping set: Delta + Theta + Alpha + Beta + Gamma ~ 1.0
    (Alpha1/Alpha2, Beta1/Beta2/Beta3/HighBeta are sub-bands and should NOT
    be included in the sum.)

    Note: total power denominator covers 0.5-50 Hz but Delta starts at 1 Hz,
    so the 0.5-1 Hz sub-delta range is in the denominator but not in any
    band. This means sums will be slightly below 1.0 (typically 0.80-0.95).
    """
    non_overlapping = {"Delta", "Theta", "Alpha", "Beta", "Gamma"}
    standard_channels = {
        "Fp1", "Fp2", "F7", "F3", "Fz", "F4", "F8",
        "T3", "C3", "Cz", "C4", "T4",
        "T5", "P3", "Pz", "P4", "T6", "O1", "O2",
    }

    cells = [
        c for c in norms
        if c.metric == "relative_power" and c.band in non_overlapping
        and c.channel in standard_channels and c.n >= 5
    ]

    # Group by (bin, condition, channel)
    groups = defaultdict(dict)
    for c in cells:
        groups[(c.bin, c.condition, c.channel)][c.band] = c.mean

    results = []
    violations = []
    for key, band_means in sorted(groups.items()):
        if len(band_means) < 4:  # need most bands present
            continue
        total = sum(band_means.values())
        # Wide tolerance: sub-delta (0.5-1 Hz) is in the denominator but
        # not in any band, so sums are typically 0.75-0.95
        correct = 0.70 <= total <= 1.10
        entry = {
            "bin": key[0],
            "condition": key[1],
            "channel": key[2],
            "sum_relative_power": round(total, 3),
            "bands_present": len(band_means),
            "correct": correct,
        }
        results.append(entry)
        if not correct:
            violations.append(entry)

    return {
        "check": "Relative power sums to ~1.0",
        "description": "Sum of relative power across non-overlapping bands should be ~1.0 (tolerance: 0.85-1.15)",
        "reference": "Basic spectral sanity check",
        "n_tested": len(results),
        "n_correct": len(results) - len(violations),
        "pass": len(violations) == 0,
        "violations": violations[:5],
    }


def check_gsf_consistency(norms) -> dict:
    """GSF should be similar across age bins (it's amplifier-dependent, not age-dependent).

    If GSF varies significantly by age, it suggests a systematic issue
    (e.g., different recording setups for different age groups).
    """
    cells = [
        c for c in norms
        if c.metric == "gsf" and c.channel == "_subject" and c.n >= 5
    ]

    if not cells:
        return {
            "check": "GSF consistency across age",
            "pass": None,
            "note": "No GSF cells found",
        }

    by_cond = defaultdict(list)
    for c in cells:
        by_cond[c.condition].append(c)

    results = {}
    for cond, cond_cells in sorted(by_cond.items()):
        means = [c.mean for c in cond_cells]
        spread = max(means) - min(means) if means else 0
        cv = float(np.std(means) / abs(np.mean(means))) if means and np.mean(means) != 0 else None

        results[cond] = {
            "bins": [c.bin for c in cond_cells],
            "gsf_means": [round(c.mean, 2) for c in cond_cells],
            "spread": round(spread, 2),
            "cv": round(cv, 3) if cv is not None else None,
            "consistent": cv is not None and cv < 0.10,  # CV < 10%
        }

    return {
        "check": "GSF consistency across age bins",
        "description": "GSF should be similar across age bins (CV < 10%). Large variation suggests equipment differences.",
        "reference": "GSF reflects amplifier gain and skull thickness, not age-related neural changes",
        "pass": all(v["consistent"] for v in results.values()),
        "by_condition": results,
    }


# ── Main ────────────────────────────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(
        description="Validate normative database against published literature findings",
    )
    parser.add_argument(
        "subjects_dir",
        type=Path,
        help="Path to subjects/ checkpoint directory from build_norms.py",
    )
    parser.add_argument(
        "--output", "-o",
        type=Path,
        default=None,
        help="Write validation report as JSON",
    )
    parser.add_argument(
        "--age-bins",
        type=int,
        nargs="+",
        default=_DEFAULT_AGE_BINS,
        help="Age bin edges (default: decade bins 20-80)",
    )

    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(message)s")

    if not args.subjects_dir.exists():
        logger.error("Directory not found: %s", args.subjects_dir)
        sys.exit(1)

    logger.info("Loading subjects from %s ...", args.subjects_dir)
    subjects = load_subjects(args.subjects_dir)
    logger.info("  %d subject-condition records loaded", len(subjects))

    logger.info("Building normative distributions ...")
    norms = build_normative(subjects, age_bins=args.age_bins)
    logger.info("  %d normative cells", len(norms))

    # Run all checks
    checks = [
        ("alpha_posterior_dominance", check_alpha_posterior_dominance),
        ("eo_ec_alpha", check_eo_ec_alpha),
        ("aperiodic_exponent_range", check_aperiodic_exponent_range),
        ("aperiodic_age_flattening", check_aperiodic_age_flattening),
        ("iaf_range", check_iaf_range),
        ("theta_beta_ratio_range", check_theta_beta_ratio_range),
        ("relative_power_sums", check_relative_power_sums),
        ("gsf_consistency", check_gsf_consistency),
    ]

    report = {}
    summary = []

    for name, check_fn in checks:
        logger.info("\n=== %s ===", name)
        result = check_fn(norms)
        report[name] = result

        logger.info("  %s", result.get("description", ""))
        logger.info("  Reference: %s", result.get("reference", ""))

        passed = result.get("pass")
        if passed is True:
            status = "PASS"
        elif passed is False:
            status = "** FAIL **"
        else:
            status = "SKIP"

        detail = ""
        if "n_tested" in result:
            n_ok = result.get("n_correct", result.get("n_in_range", "?"))
            detail = f" ({n_ok}/{result['n_tested']} cells)"
        if "median_ec_eo_ratio" in result and result["median_ec_eo_ratio"]:
            detail += f" median EC/EO ratio: {result['median_ec_eo_ratio']}"
        if result.get("note"):
            detail = f" — {result['note']}"

        logger.info("  Result: %s%s", status, detail)

        if result.get("violations"):
            for v in result["violations"][:3]:
                logger.info("    Violation: %s", v)

        if result.get("by_condition"):
            for cond, v in result["by_condition"].items():
                if "correlation_r" in v:
                    logger.info("    %s: r=%.3f (p=%.4f) %s",
                              cond.upper(), v["correlation_r"], v["correlation_p"],
                              "PASS" if v.get("negative_trend") else "FAIL")

        summary.append({"check": name, "status": status})

    # Final summary
    logger.info("\n" + "=" * 60)
    logger.info("LITERATURE VALIDATION SUMMARY")
    logger.info("=" * 60)
    for s in summary:
        logger.info("  %-40s %s", s["check"], s["status"])

    n_pass = sum(1 for s in summary if s["status"] == "PASS")
    n_fail = sum(1 for s in summary if s["status"] == "** FAIL **")
    n_skip = sum(1 for s in summary if s["status"] == "SKIP")
    logger.info("\n  %d PASS, %d FAIL, %d SKIP", n_pass, n_fail, n_skip)

    if n_fail == 0:
        logger.info("  All checks passed — norms are consistent with published literature.")
    else:
        logger.info("  Some checks failed — investigate before using these norms clinically.")

    report["summary"] = summary

    if args.output:
        with open(args.output, "w") as f:
            json.dump(report, f, indent=2, cls=_NumpyEncoder)
        logger.info("\nFull report written to %s", args.output)


if __name__ == "__main__":
    main()
