name: hello-selfhosted
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['.github/workflows/hello.yml']
jobs:
  minimal:
    runs-on: [self-hosted, Linux]
    steps: [{ run: 'echo MIN; hostname; date' }]
  full:
    runs-on: [self-hosted, Linux, X64, ci-pool]
    steps: [{ run: 'echo FULL; hostname; date' }]
